# Generated by Django 4.2.11 on 2024-04-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FullEnquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("child_name", models.CharField(max_length=255)),
                ("child_date_of_birth", models.DateField()),
                ("child_gender", models.CharField(max_length=10)),
                ("child_primary_language", models.CharField(max_length=255)),
                ("child_secondary_languages", models.CharField(max_length=255)),
                ("child_strengths", models.TextField()),
                ("child_interests", models.TextField()),
                ("child_things_important", models.TextField()),
                ("enquirer_name", models.CharField(max_length=255)),
                ("enquirer_relationship", models.CharField(max_length=255)),
                ("enquirer_email", models.EmailField(max_length=255)),
                ("enquirer_phone", models.CharField(max_length=10)),
                ("enquirer_primary_language", models.CharField(max_length=255)),
                ("enquirer_secondary_languages", models.CharField(max_length=255)),
                ("primary_support_1_name", models.CharField(max_length=255)),
                ("primary_support_1_address", models.TextField()),
                ("primary_support_1_phone", models.CharField(max_length=10)),
                ("primary_support_1_email", models.EmailField(max_length=255)),
                ("primary_support_1_relationship", models.CharField(max_length=255)),
                ("primary_support_2_name", models.CharField(max_length=255)),
                ("primary_support_2_address", models.TextField()),
                ("primary_support_2_phone", models.CharField(max_length=10)),
                ("primary_support_2_email", models.EmailField(max_length=255)),
                ("primary_support_2_relationship", models.CharField(max_length=255)),
                ("expression", models.BooleanField()),
                ("reception", models.BooleanField()),
                ("articulation", models.BooleanField()),
                ("social", models.BooleanField()),
                ("participation", models.BooleanField()),
                ("mealtimes", models.BooleanField()),
                ("stuttering", models.BooleanField()),
                ("other_goals", models.TextField()),
                ("noticed_help_needed", models.TextField()),
                ("diagnosis_primary", models.CharField(max_length=255)),
                ("diagnoses_secondary", models.CharField(max_length=255)),
                ("additional_info", models.TextField()),
                ("occupational", models.BooleanField()),
                ("psychology", models.BooleanField()),
                ("speech_other", models.BooleanField()),
                ("physio", models.BooleanField()),
                ("other_therapies", models.TextField()),
                ("family_history", models.TextField()),
                ("day_care_name", models.CharField(max_length=255)),
                ("day_care_contact", models.TextField()),
                ("school_name", models.CharField(max_length=255)),
                ("school_contact", models.TextField()),
                ("school_year", models.IntegerField()),
                ("teacher", models.CharField(max_length=255)),
                ("home_therapy", models.BooleanField()),
                ("school_therapy", models.BooleanField()),
                ("support_to_access_activity", models.BooleanField()),
                ("parent_coaching", models.BooleanField()),
                ("monday", models.BooleanField()),
                ("tuesday", models.BooleanField()),
                ("wednesday", models.BooleanField()),
                ("thursday", models.BooleanField()),
                ("friday", models.BooleanField()),
                ("private", models.BooleanField()),
                ("ndis_self_managed", models.BooleanField()),
                ("ndis_plan_managed", models.BooleanField()),
                ("ndis_number", models.CharField(max_length=255)),
                ("plan_manager_name", models.CharField(max_length=255)),
                ("plan_manager_email", models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SimpleEnquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("phone", models.CharField(max_length=10)),
                ("message", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
